### ISSUE TITLE
Làm sao để kết bạn với nó ?

### ISSUE THREAD

**Issue by k3lvinmitnick** [Tungchaphet/Chino-chan-Bot#1]
Mình đã cài đặt thành công 

4 lệnh đã sẵn sàng!
1 events đã sẵn sàng! ...

AD làm phiền cho mình hỏi chút:
1) Làm sao để kết bạn với nó ?
2) Nếu có Video hướng dẫn thì cho mình link với

**Comment by Tungchaphet** [comment]
1. Bạn dùng acc khác để kết bạn với nó nhé :>
2. https://youtu.be/CdUgIbcG_uk

**Comment by k3lvinmitnick** [comment]
/ask đang bị lỗi, các prompt khác thì OK.
1) Không rõ bạn có đang update gì ko ?
2) Làm sao để tự mình tạo ra các Q/A cho bot ?

**Comment by Tungchaphet** [comment]
Bạn thử kiểm tra lại api key của bạn có đúng ko nhé, hoặc là api key chưa thêm vô file config.js, hoặc là key của bạn hết tiền, nếu trường hợp ko đúng model của chatgpt thì bạn vô code sửa theo ý bạn nhé :>
1. Dạo này mình chưa update gì hết vì bận quá :<
2. Bạn có thể thêm lệnh bạn muốn bằng cách thêm folder vào folder commands hoặc cho trực tiếp folder có sẵn trong commands của bot
3. Lỗi tính toán :>
