### ISSUE TITLE
Mình chạy được rồi mà sao nó không rep ạ

### ISSUE THREAD

**Issue by sangdzpro2k** [Tungchaphet/Chino-chan-Bot#10]
![IMG_20240831_211144](https://github.com/user-attachments/assets/ab28669a-4753-4e69-8530-8dc7e8116273)

**Comment by eptprofile** [comment]
Messenger đã có e2ee từ 9 tháng trước, xem tại đây https://github.com/misonomikadev/messenger-api.js/issues/16

Chính vì cái mã hoá 2 chiều này khiến cho bot ko thể nhận tin nhắn, xử lý tin nhắn này thì bên mình vẫn đang nghiên cứu ạ, bạn thử nhắn bot tại kênh ko có e2ee đi
