### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by thangcodon** [Tungchaphet/Chino-chan-Bot#11]
Mình có đổi lại code index js như này vì nó gặp lỗi không thể biết được const { Client } = require('messenger-api.js')
const client = new Client({ online: true }) 
const config = require('./config/config.js') 
const fs = require('fs')

client.on('ready', async (bot) => {
    try {
        for (const file of fs.readdirSync('./handlers')) { 
            if (!file.endsWith('.js')) continue 
            await require(`./handlers/${file}`)(bot) 
        }
        console.log(`${bot.user.username} đã đội mồ sống dậy.`) 
    } catch (error) {
        console.error('Error in ready event:', error)
    }
})

client.login(config.credentials, true).catch(error => {
    console.error('Login failed:', error)
})

process.on('unhandledRejection', (reason, promise) => {
    console.log('Unhandled Rejection at:', promise, 'reason:', reason)
}), sau khi đổi thành trên thì lỗi nó đã in ra gõ cho mình, cho mình hỏi cách khắc phục với npm start

> chino-chan@1.0.0 start
> node index.js

(node:29835) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Login failed: {
  __ar: 1,
  error: 1357004,
  errorSummary: 'Rất tiếc, đã xảy ra lỗi',
  errorDescription: 'Vui lòng thử đóng và mở lại cửa sổ trình duyệt của bạn.',
  isNotCritical: 1,
  payload: null,
  lid: '7417785377949421056'
}
~/.../downloads/bot $

**Comment by eptprofile** [comment]
Facebook thay đổi khá nhiều nên API bị breaking change khá nhiều nên login không được.
Mà cho dù có vô đc đi nữa thì cũng ko dùng đc do có mã hoá 2 chiều của messenger (này mình vẫn đang nghiên cứu nhưng sắp đi vào bế tắc rồi ;-;)
Nếu mình có thời gian thì mình sẽ nghiên cứu thêm cho v2 của thư viện nhé.
