### ISSUE TITLE
 lỗi  Object.assign() 

### ISSUE THREAD

**Issue by lebakhai13** [Tungchaphet/Chino-chan-Bot#3]
Finished pulling Docker container image
v18.15.0
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; /usr/local/bin/node /home/container/${BOT_JS_FILE}

up to date, audited 135 packages in 2s
9 packages are looking for funding
  run `npm fund` for details
2 moderate severity vulnerabilities
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
/home/container/node_modules/messenger-api.js/src/client/Client.js:42
                    this.user = new ClientUser(this, Object.assign(clientUser[clientID], { id: clientID }))
                                                            ^
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at Timeout._onTimeout (/home/container/node_modules/messenger-api.js/src/client/Client.js:42:61)
Node.js v18.15.0

**Comment by lebakhai13** [comment]
> Lỗi khó xuất hiện nhất tôi từng thấy =)))

Chạy trên 1 host **[Pterodactyl®](https://pterodactyl.io/) © 2015 - 2023**  24/7 miễn phí

**Comment by Tungchaphet** [comment]
Chả liên quan đến issue này, và tôi có sẵn 2 host rồi, cảm ơn :>

**Comment by lebakhai13** [comment]
> Chả liên quan đến issue này, và tôi có sẵn 2 host rồi, cảm ơn :>

Tôi không chạy npm i

**Comment by lebakhai13** [comment]
> npm i là tải package trên npm mà bạn :>

vậy có thể do thiếu package không?

**Comment by Tungchaphet** [comment]
Nếu trước khi bạn bắt đầu bot mà bạn npm i (hay npm install) thì đều tải tất cả các package của code này rồi

**Comment by lebakhai13** [comment]
nên dùng bản nodejs bao nhiêu

**Comment by Tungchaphet** [comment]
v18.9 trở lên nhé :>
